### ISSUE TITLE
[UX] Application resize

### ISSUE THREAD

**Issue by yewshengkai** [CS2103AUG2017-W10-B2/main#127]
Users with small screen resolution are unable to view the whole application.
- Application on-start require to use windows `maximize button` to view the whole application.
- Application does not allow horizontal resize to suitable screen resolution.

![image](https://user-images.githubusercontent.com/31110233/32362130-e0cd259a-c0a1-11e7-932c-35d955e7d4b3.png)

**Comment by KeithSOC** [comment]
Thanks :)
Has been fixed in #114.
