### ISSUE TITLE
[UX] Error/CommandUsage message not available on command features when `help` window is open

### ISSUE THREAD

**Issue by yewshengkai** [CS2103AUG2017-W10-B2/main#128]
Error/CommandUsage message not available when command uses no/wrong input[option].
e.g. theme -1 | add ""
e.g. add n/John p/ads e/asd

**Update: when `HELP` window is open, the commandusage message will be block or not available**
![image](https://user-images.githubusercontent.com/31110233/32362227-aeb9f3d4-c0a2-11e7-9be7-c93f5610a744.png)

**Comment by KeithSOC** [comment]
@yewshengkai Hmmm, it is working as it should:

![capture](https://user-images.githubusercontent.com/2218315/32362788-e383ce38-c0a6-11e7-83f4-24eaf1d686d3.PNG)

**Comment by yewshengkai** [comment]
Update: just figured the 'help' window block the message and some functionality of commands.

**Comment by KeithSOC** [comment]
@yewshengkai Still couldn't produce the bug when `help` window is open. Could you please let us know the full steps to reproduce the problem?
Thanks!

**Comment by yewshengkai** [comment]
@KeithSOC On application start, try executing `help` command (without closing the window) and input other command.
