### ISSUE TITLE
[UX] `Sort -recent` command

### ISSUE THREAD

**Issue by yewshengkai** [CS2103AUG2017-W10-B2/main#129]
find bob
According to the `sort` examples,
"lists all the person that contain the keyword bob, sorted based on when they were last accessed"

After adding multiple user of the first name `John`, and edit their information, `sort -recent` does not list information correctly.

e.g.
add n/John Doe ....
add n/John Lima ....
add n/John Feh ....

find John
-display-
[1] John Doe
[2] John Lima
[3] John Feh
edit 2 p/1234
sort -recent
-returns similar result-
[1] John Doe
[2] John Lima
[3] John Feh

**Comment by KeithSOC** [comment]
Thanks :) 
This is because `sort recent` feature was slated to be `[Coming in v2.0]` in UG.
