### ISSUE TITLE
[UX] social interation

### ISSUE THREAD

**Issue by yewshengkai** [CS2103AUG2017-W10-B2/main#132]
How does this work?
command not executed.

e.g. facebook connect - not working
e.g. facebook r.cross10 - not working
![image](https://user-images.githubusercontent.com/31110233/32363175-e9421300-c0a8-11e7-8908-621bfc3edf55.png)

![image](https://user-images.githubusercontent.com/31110233/32362833-186a6d1e-c0a7-11e7-98eb-16c168a3676b.png)

**Comment by KeithSOC** [comment]
Thanks @yewshengkai! 
Issue surfaced in #111. Apparently a bug is causing this issue - currently, only the alias: `fb connect` is working.
