### ISSUE TITLE
[UX] `select` command

### ISSUE THREAD

**Issue by yewshengkai** [CS2103AUG2017-W10-B2/main#134]
Select command not working as intended. 
**Update: Not working when `Help` window is open**
![image](https://user-images.githubusercontent.com/31110233/32362938-b0c66248-c0a7-11e7-8e46-52864d0b9ff6.png)

**Comment by KeithSOC** [comment]
Hello @yewshengkai! Thanks for notifying us of our bugs :) May I know the reason why you've closed this issue?

**Comment by yewshengkai** [comment]
Hi @KeithSOC, its the same issue as #128 whereby "Update: Not working when Help window is open". Apologize for the late reply.
