### ISSUE TITLE
Unfav command not working properly

### ISSUE THREAD

**Issue by caoliangnus** [CS2103AUG2017-W10-B2/main#136]
![image](https://user-images.githubusercontent.com/30979259/32363103-8d46b02e-c0a8-11e7-89e0-17bdb9df5884.png)

![image](https://user-images.githubusercontent.com/30979259/32363090-7b3116c2-c0a8-11e7-8711-8828ac860fc9.png)

When i executed "fav 1 2 3" and then "unfav 1 2 3", something wrong with the unfav command

**Comment by marvinchin** [comment]
Likely related to #110 @KeithSOC

**Comment by KeithSOC** [comment]
Fixed in #141.
