### ISSUE TITLE
"facebook connect" command not recognized

### ISSUE THREAD

**Issue by nguyenvanhoang7398** [CS2103AUG2017-W10-B2/main#137]
![image](https://user-images.githubusercontent.com/21237688/32363638-4628d692-c0ab-11e7-8f28-e4890c0021fa.png)

**Comment by KeithSOC** [comment]
Thanks guys! :)

Similar to issue #111. @alexfoodw Please note. :)

**Comment by alexfoodw** [comment]
noted!
