### ISSUE TITLE
"fb alex" not recognized

### ISSUE THREAD

**Issue by nguyenvanhoang7398** [CS2103AUG2017-W10-B2/main#138]
![image](https://user-images.githubusercontent.com/21237688/32363722-9c7a0c46-c0ab-11e7-8b6b-86384148ce09.png)

**Comment by KeithSOC** [comment]
This command is non-existent. Were you confused by this: https://github.com/CS2103AUG2017-W10-B2/main/blob/master/docs/UserGuide.adoc#441-representing-social-media-accounts? Do let us know. Thanks!

**Comment by marvinchin** [comment]
Will update user guide to better indicate that this is not a command
